version: "3.8"
 
services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=MySql2020!
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
 
  app:
    build: .
    command: bash start.sh
    environment:
      - DB_PASSWORD=MySql2020!
    ports:
      - "3000:3000"
    volumes:
      - .:/nexaaspi
      - gems:/gems
    depends_on:
      - db
    
volumes:
  mysql:
  gems: